//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eshop.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class memberRole
    {
        public int memberRole1 { get; set; }
        public Nullable<int> customerId { get; set; }
        public Nullable<int> roleId { get; set; }
    }
}
